name: Generate Keystore

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Generate Keystore
        run: |
          keytool -genkeypair -v \
            -keystore myime.keystore \
            -storepass myime123 \
            -alias myime \
            -keypass myime123 \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=MyIME, OU=Personal, O=Personal, L=City, ST=State, C=CN"

      - name: Upload Keystore
        uses: actions/upload-artifact@v4
        with:
          name: keystore
          path: myime.keystore